name: Build custom Alpine image

on:
  push:
  workflow_dispatch:
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      security-events: write
      id-token: write
      attestations: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: crazy-max/ghaction-setup-docker@v3
        with:
          daemon-config: |
            {
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push container image
        uses: docker/build-push-action@v6
        id: push
        with:
          platforms: linux/amd64,linux/arm64
          outputs: |
            type=docker,rewrite-timestamp=true
            type=image,push=true,rewrite-timestamp=true
          provenance: true
          sbom: true
          tags: ghcr.io/${{ github.repository }}/alpine:custom
          build-args:
            BUILDKIT_SBOM_SCAN_STAGE=true
          cache-from: type=gha,scope=alpine
          cache-to: type=gha,mode=max,scope=alpine
          no-cache: ${{ github.event_name == 'workflow_dispatch' }}
        env:
          SOURCE_DATE_EPOCH: 0

      - name: Attest provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ghcr.io/${{ github.repository }}/alpine
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      - name: Generate SBOM
        run: |
          docker buildx imagetools inspect ghcr.io/${{ github.repository }}/alpine:custom --format '{{ json (index .SBOM "linux/amd64").SPDX }}' > sbom-amd64.spdx.json
          docker buildx imagetools inspect ghcr.io/${{ github.repository }}/alpine:custom --format '{{ json (index .SBOM "linux/arm64").SPDX }}' > sbom-arm64.spdx.json

      - name: Attest SBOM
        uses: actions/attest-sbom@v1
        with:
          subject-name: ghcr.io/${{ github.repository }}/alpine
          subject-digest: ${{ steps.push.outputs.digest }}
          sbom-path: 'sbom-amd64.spdx.json'
          push-to-registry: true

      - name: Attest SBOM
        uses: actions/attest-sbom@v1
        with:
          subject-name: ghcr.io/${{ github.repository }}/alpine
          subject-digest: ${{ steps.push.outputs.digest }}
          sbom-path: 'sbom-arm64.spdx.json'
          push-to-registry: true
